# ----
# Site

title: Pretendentas
description: Pretendentas API dokumentacija.
baseurl: '/api'
url: https://pretendentas.github.io
google_analytics_key:

collections:
  info:
    title: Dokumentacija
    position: 1
  user:
    title: Vartotojo informacija
    position: 2
  orders:
    title: Užsakymai
    position: 3
  invoices:
    title: Sąskaitos
    position: 4
  categories:
    title: Prekių kategorijos
    position: 5
  products:
    title: Prekių informacija
    position: 6
  producttypes:
    title: Prekių tipai
    position: 7
  manufacturers:
    title: Gamintojai
    position: 8
  paymenttypes:
    title: Apmokėjimo būdai
    position: 9
  deliverytypes:
    title: Pristatymo būdai
    position: 10
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
# -----
# Build


# -----------
# CloudCannon

version: 3.0.3
